import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    brand: "HARIR",
    home: "Home",
    shop: "Shop",
    collections: "Collections",
    sale: "Sale",
    latestOffers: "Latest Offers",
    categories: "Categories",
    lookbook: "Lookbook",
    wishlist: "Wishlist",
    search: "Search products",
    login: "Login",
    logout: "Logout",
    language: "العربية",
    newSeason: "New season",
    heroTitle: "Define your style",
    heroDescription: "Modern womenswear for every occasion. Clean lines, considered fabrics, and pieces that last beyond the season.",
    shopNow: "Shop now",
    newCollection: "New collection",
    collectionDescription: "The latest cuts, built to move from morning to night.",
    essentials: "Essentials",
    essentialsDescription: "Quiet pieces for everyday wear.",
    summerCollection: "Summer collection",
    specialOffers: "Special offers",
    offersDescription: "Selected pieces, reduced for a limited time.",
    addItem: "Add Item",
    addedCart: "Added to cart",
    inStock: "in stock",
    off: "off",
    removeWishlist: "Remove from wishlist",
    addWishlist: "Add to wishlist",
    loadingProducts: "Loading products...",
    noProducts: "No products found.",
    loadError: "We could not load the catalog. Please try again.",
    account: "Account",
    welcomeBack: "Welcome back",
    loginAccount: "Login to your account",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    createAccount: "Create account",
    cancel: "Cancel",
    joinCollection: "Join the collection",
    name: "Name",
    confirmPassword: "Confirm password",
    register: "Register",
    alreadyAccount: "Already have an account",
    fillFields: "Please fill in all fields",
    passwordsMatch: "Passwords do not match",
    loginSuccess: "Login Success",
    registerSuccess: "Register Success",
    logoutSuccess: "Logout Success",
    cart: "Your cart",
    clearAll: "Clear all",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    item: "item",
    items: "items",
    emptyCart: "Your cart is empty",
    continueShopping: "Continue shopping",
    orderSummary: "Order summary",
    shipping: "Shipping",
    free: "Free",
    total: "Total",
    checkout: "Checkout",
    chooseWallet: "Choose wallet",
    paymentWallet: "Payment wallet",
    walletBalance: "Available balance",
    confirmPayment: "Confirm payment",
    close: "Close",
    temporaryCheckout: "Temporary checkout",
    productNotFound: "Product not found",
    loadingProduct: "Loading product...",
    back: "Back",
    savedPieces: "Saved pieces.",
    emptyWishlist: "Your wishlist is empty",
    browseShop: "Browse the shop",
    resultsFor: "Results for",
    clearSearch: "Clear search",
    fullCatalog: "The full catalog, ready to wear.",
    category: "Category",
    exploreCollection: "Explore our latest collection",
    footerDescription: "Modern womenswear. Considered pieces, made to last beyond the season.",
    support: "Support",
    follow: "Follow",
    followDescription: "Stay close for new drops and quiet restocks.",
    returns: "Returns",
    privacy: "Privacy Policy",
    lookbookDescription: "Looks crafted for modern days — comfort, line, and quiet confidence.",
    urbanStreet: "Urban Street",
    urbanStreetDescription: "Bold layers with modern attitude.",
    minimalFit: "Minimal Fit",
    minimalFitDescription: "Clean lines for everyday elegance.",
    winterVibes: "Winter Vibes",
    winterVibesDescription: "Stay warm without losing style.",
  },
  ar: {
    brand: "حرير",
    home: "الرئيسية",
    shop: "المتجر",
    collections: "المجموعات",
    sale: "التخفيضات",
    latestOffers: "أحدث العروض",
    categories: "التصنيفات",
    lookbook: "الإطلالات",
    wishlist: "المفضلة",
    search: "ابحث عن المنتجات",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    language: "English",
    newSeason: "الموسم الجديد",
    heroTitle: "عرّف أسلوبك",
    heroDescription: "أزياء عصرية لكل مناسبة. خطوط نظيفة، أقمشة مختارة، وقطع تدوم لأكثر من موسم.",
    shopNow: "تسوق الآن",
    newCollection: "المجموعة الجديدة",
    collectionDescription: "أحدث القصات المصممة لترافقك من الصباح حتى المساء.",
    essentials: "الأساسيات",
    essentialsDescription: "قطع هادئة لإطلالتك اليومية.",
    summerCollection: "مجموعة الصيف",
    specialOffers: "عروض خاصة",
    offersDescription: "قطع مختارة بأسعار مخفضة لفترة محدودة.",
    addItem: "أضف للسلة",
    addedCart: "تمت الإضافة إلى السلة",
    inStock: "متوفر",
    off: "خصم",
    removeWishlist: "إزالة من المفضلة",
    addWishlist: "إضافة للمفضلة",
    loadingProducts: "جارٍ تحميل المنتجات...",
    noProducts: "لم يتم العثور على منتجات.",
    loadError: "تعذر تحميل المنتجات. حاول مرة أخرى.",
    account: "الحساب",
    welcomeBack: "مرحبًا بعودتك",
    loginAccount: "سجّل الدخول إلى حسابك",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    cancel: "إلغاء",
    joinCollection: "انضم إلى المجموعة",
    name: "الاسم",
    confirmPassword: "تأكيد كلمة المرور",
    register: "تسجيل",
    alreadyAccount: "لديك حساب بالفعل؟",
    fillFields: "يرجى ملء جميع الحقول",
    passwordsMatch: "كلمتا المرور غير متطابقتين",
    loginSuccess: "تم تسجيل الدخول",
    registerSuccess: "تم إنشاء الحساب",
    logoutSuccess: "تم تسجيل الخروج",
    cart: "سلة التسوق",
    clearAll: "مسح الكل",
    decreaseQuantity: "تقليل الكمية",
    increaseQuantity: "زيادة الكمية",
    item: "عنصر",
    items: "عناصر",
    emptyCart: "سلة التسوق فارغة",
    continueShopping: "متابعة التسوق",
    orderSummary: "ملخص الطلب",
    shipping: "الشحن",
    free: "مجاني",
    total: "الإجمالي",
    checkout: "إتمام الشراء",
    chooseWallet: "اختر المحفظة",
    paymentWallet: "محفظة الدفع",
    walletBalance: "الرصيد المتاح",
    confirmPayment: "تأكيد الدفع",
    close: "إغلاق",
    temporaryCheckout: "إتمام شراء مؤقت",
    productNotFound: "المنتج غير موجود",
    loadingProduct: "جارٍ تحميل المنتج...",
    back: "رجوع",
    savedPieces: "قطعك المحفوظة.",
    emptyWishlist: "قائمة المفضلة فارغة",
    browseShop: "تصفح المتجر",
    resultsFor: "نتائج البحث عن",
    clearSearch: "مسح البحث",
    fullCatalog: "الكتالوج الكامل جاهز للتسوق.",
    category: "التصنيف",
    exploreCollection: "اكتشف أحدث مجموعاتنا",
    footerDescription: "أزياء عصرية بقطع مختارة صُممت لتدوم لأكثر من موسم.",
    support: "المساعدة",
    follow: "تابعنا",
    followDescription: "ابقَ قريبًا من الإصدارات الجديدة وإعادة توفير القطع.",
    returns: "الاسترجاع",
    privacy: "سياسة الخصوصية",
    lookbookDescription: "إطلالات مصممة للأيام العصرية، تجمع بين الراحة والخطوط الواضحة والثقة الهادئة.",
    urbanStreet: "أناقة حضرية",
    urbanStreetDescription: "طبقات جريئة بروح عصرية.",
    minimalFit: "إطلالة بسيطة",
    minimalFitDescription: "خطوط نظيفة لأناقة يومية.",
    winterVibes: "أجواء شتوية",
    winterVibesDescription: "ابقَ دافئًا دون التنازل عن أسلوبك.",
  },
};

const LanguageContext = createContext(null);

const arabicCategories = {
  beauty: "الجمال",
  fragrances: "العطور",
  furniture: "الأثاث",
  groceries: "البقالة",
  "home-decoration": "ديكور المنزل",
  laptops: "أجهزة اللابتوب",
  "mens-shirts": "قمصان رجالية",
  "mens-shoes": "أحذية رجالية",
  "mens-watches": "ساعات رجالية",
  motorcycle: "الدراجات النارية",
  "skin-care": "العناية بالبشرة",
  smartphones: "الهواتف الذكية",
  "sports-accessories": "إكسسوارات رياضية",
  sunglasses: "النظارات الشمسية",
  tablets: "الأجهزة اللوحية",
  tops: "الملابس العلوية",
  vehicle: "المركبات",
  "womens-bags": "حقائب نسائية",
  "womens-dresses": "فساتين نسائية",
  "womens-jewellery": "مجوهرات نسائية",
  "womens-shoes": "أحذية نسائية",
  "womens-watches": "ساعات نسائية",
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("language") || "en");
  const direction = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    document.title = language === "ar" ? "حرير — عرّف أسلوبك" : "HARIR — Define your style";
  }, [language, direction]);

  const value = useMemo(() => ({
    language,
    direction,
    toggleLanguage: () => setLanguage((current) => current === "en" ? "ar" : "en"),
    t: (key) => translations[language][key] || translations.en[key] || key,
    categoryName: (slug, fallback) => language === "ar" ? arabicCategories[slug] || fallback || slug : fallback || slug,
  }), [language, direction]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
